import { Titillium_Web } from 'next/font/google';
import Head from 'next/head';
import clsx from 'clsx';
import Header from '@/components/Header/Header';
import styles from '@/styles/Home.module.css';

const titillium = Titillium_Web({ weight: ['400', '700'], subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Maxim Titov</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={clsx(styles.main, titillium.className)}>
        <Header />
        <h2>I am a senior frontend developer</h2>
      </main>
    </>
  );
}
